"""add_is_clarification_to_message

Revision ID: 950dc1877092
Revises: 5339dabc08ce
Create Date: 2026-06-26 17:53:44.941193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '950dc1877092'
down_revision: Union[str, Sequence[str], None] = '5339dabc08ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_clarification', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_clarification')
    # ### end Alembic commands ###
